/** Stable H0a auth error classes — safe for logs/metrics (no token/key material). */

export const TokenErrorCode = Object.freeze({
  TOKEN_MALFORMED: 'TOKEN_MALFORMED',
  TOKEN_SIGNATURE_INVALID: 'TOKEN_SIGNATURE_INVALID',
  TOKEN_ALG_UNSUPPORTED: 'TOKEN_ALG_UNSUPPORTED',
  TOKEN_ALG_NONE_REJECTED: 'TOKEN_ALG_NONE_REJECTED',
  TOKEN_KEY_UNKNOWN: 'TOKEN_KEY_UNKNOWN',
  TOKEN_ISSUER_INVALID: 'TOKEN_ISSUER_INVALID',
  TOKEN_AUDIENCE_INVALID: 'TOKEN_AUDIENCE_INVALID',
  TOKEN_AUTHORIZED_PARTY_INVALID: 'TOKEN_AUTHORIZED_PARTY_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_NOT_YET_VALID: 'TOKEN_NOT_YET_VALID',
  TOKEN_IAT_IN_FUTURE: 'TOKEN_IAT_IN_FUTURE',
  TOKEN_SUBJECT_MISSING: 'TOKEN_SUBJECT_MISSING',
  TOKEN_SESSION_ID_MISSING: 'TOKEN_SESSION_ID_MISSING',
  TOKEN_UNSIGNED: 'TOKEN_UNSIGNED',
  IDENTITY_MAPPING_NOT_FOUND: 'IDENTITY_MAPPING_NOT_FOUND',
  IDENTITY_MAPPING_DISABLED: 'IDENTITY_MAPPING_DISABLED',
  IDENTITY_MAPPING_AMBIGUOUS: 'IDENTITY_MAPPING_AMBIGUOUS',
  IDENTITY_PROVIDER_MISMATCH: 'IDENTITY_PROVIDER_MISMATCH',
  IDENTITY_ISSUER_MISMATCH: 'IDENTITY_ISSUER_MISMATCH',
  SESSION_POLICY_REJECTED: 'SESSION_POLICY_REJECTED',
  SESSION_INACTIVITY_EXCEEDED: 'SESSION_INACTIVITY_EXCEEDED',
  SESSION_MAX_LIFETIME_EXCEEDED: 'SESSION_MAX_LIFETIME_EXCEEDED',
  SESSION_MULTI_ACTIVE_REJECTED: 'SESSION_MULTI_ACTIVE_REJECTED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  PRINCIPAL_TYPE_REJECTED: 'PRINCIPAL_TYPE_REJECTED',
  PASSKEY_ASSURANCE_REQUIRED: 'PASSKEY_ASSURANCE_REQUIRED',
  EMAIL_OTP_OPERATIONAL_ACCESS_REJECTED: 'EMAIL_OTP_OPERATIONAL_ACCESS_REJECTED',
});

export function fail(code, detail) {
  return { ok: false, code, detail: detail || code };
}
