#!/usr/bin/env bash
# Idempotent apply — Vercel + Supabase + Resend. Checkdomain DNS skipped (no paid API).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"
load_config_if_present

export DTH_EVID_ROOT="${DTH_EVID_ROOT:-/tmp/dth-07b-credential-bootstrap-and-apply}"
STATUS_DIR="${DTH_EVID_ROOT}/status"
mkdir -p "$STATUS_DIR"

YES=NO
for a in "$@"; do [[ "$a" == "--yes" ]] && YES=YES; done
[[ "$YES" == "YES" ]] || {
  log "Refusing apply without --yes. Run plan.sh first."
  exit 2
}

# Preflight (generates internal secrets, checks external)
if ! "$SCRIPT_DIR/preflight.sh"; then
  exit $?
fi
load_config_if_present

need=(SUPABASE_ACCESS_TOKEN RESEND_API_KEY CONTROLLED_TEST_EMAIL)
for v in "${need[@]}"; do
  if [[ -z "${!v-}" ]]; then
    exit_token AUTOMATION_CREDENTIALS_REQUIRED
  fi
done

# Ensure mock mail path without custom-domain DNS at Checkdomain
export LEADS_MAIL_MODE="${LEADS_MAIL_MODE:-mock}"
export LEADS_FROM_EMAIL="${LEADS_FROM_EMAIL:-DeinTarifheld <onboarding@resend.dev>}"
log "DNS_AUTOMATION=SKIPPED CHECKDOMAIN_API_REQUIRED=NO LEADS_MAIL_MODE=$LEADS_MAIL_MODE"

PROJECT_NAME="${SUPABASE_PROJECT_NAME:-deintarifheld-phase-a}"
VERCEL_NAME="${VERCEL_PROJECT_NAME:-deintarifheld-leads-api}"
REGION="${SUPABASE_REGION:-eu-central-1}"

# --- Supabase org discovery ---
log "SUPABASE_ORG_DISCOVERY"
ORGS_JSON="$(curl -sS https://api.supabase.com/v1/organizations \
  -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" || echo '[]')"
printf '%s\n' "$ORGS_JSON" | jq '[.[]? | {id, name}]' 2>/dev/null \
  | redact > "$STATUS_DIR/supabase-orgs.redacted.json" || true
ORG_COUNT="$(printf '%s' "$ORGS_JSON" | jq 'if type=="array" then length else 0 end' 2>/dev/null || echo 0)"
if [[ -z "${SUPABASE_ORG_ID-}" || "${SUPABASE_ORG_ID}" == "" ]]; then
  if [[ "$ORG_COUNT" == "1" ]]; then
    SUPABASE_ORG_ID="$(printf '%s' "$ORGS_JSON" | jq -r '.[0].id')"
    log "SUPABASE_ORG_AUTOSELECTED=YES"
  elif [[ "$ORG_COUNT" == "0" ]]; then
    exit_token SUPABASE_PROVISIONING_FAILED
  else
    log "SUPABASE_ORG_SELECTION_REQUIRED org_count=$ORG_COUNT"
    exit_token SUPABASE_ORG_SELECTION_REQUIRED
  fi
fi

log "SUPABASE_PROJECT_DISCOVERY"
LIST_JSON="$(curl -sS https://api.supabase.com/v1/projects \
  -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" || echo '[]')"
printf '%s\n' "$LIST_JSON" | jq '[.[]? | {id, name, region}]' 2>/dev/null \
  | redact > "$STATUS_DIR/supabase-projects.redacted.json" || true

EXISTING_REF="$(printf '%s' "$LIST_JSON" | jq -r --arg n "$PROJECT_NAME" '
  (if type=="array" then . else [] end)
  | map(select(.name==$n)) | .[0].id // empty
')"

if [[ -n "$EXISTING_REF" ]]; then
  log "SUPABASE_ACTION=REUSE"
  SUPABASE_ACTION=REUSE
else
  # auto-generate DB password into config.env without printing
  if [[ -z "${SUPABASE_DB_PASSWORD-}" ]]; then
    umask 077
    cfg="$ROOT/infra/phase-a/config.env"
    touch "$cfg"; chmod 0600 "$cfg"
    pw="$(openssl rand -base64 32 | tr -d '\n=/+' | head -c 32)"
    if grep -q '^SUPABASE_DB_PASSWORD=' "$cfg"; then
      grep -v '^SUPABASE_DB_PASSWORD=' "$cfg" > "${cfg}.tmp" || true
      mv "${cfg}.tmp" "$cfg"
    fi
    # write via python to avoid argv leakage of password in ps
    python3 - "$cfg" "$pw" <<'PY'
import sys
from pathlib import Path
p=Path(sys.argv[1]); pw=sys.argv[2]
lines=[ln for ln in p.read_text().splitlines() if not ln.startswith('SUPABASE_DB_PASSWORD=')]
lines.append(f'SUPABASE_DB_PASSWORD={pw}')
p.write_text('\n'.join(lines)+'\n'); p.chmod(0o600)
PY
    unset pw
    load_config_if_present
    log "SUPABASE_DB_PASSWORD_AUTOGENERATED=YES VALUE_PRINTED=NO"
  fi
  log "SUPABASE_ACTION=CREATE cost_gate_eur=0"
  curl -sS -X POST 'https://api.supabase.com/v1/projects' \
    -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d "$(jq -n --arg name "$PROJECT_NAME" --arg org "$SUPABASE_ORG_ID" --arg region "$REGION" --arg db "$SUPABASE_DB_PASSWORD" \
      '{name:$name,organization_id:$org,region:$region,db_pass:$db}')" \
    > "$STATUS_DIR/supabase-create.raw.json"
  EXISTING_REF="$(jq -r '.id // empty' "$STATUS_DIR/supabase-create.raw.json")"
  redact < "$STATUS_DIR/supabase-create.raw.json" > "$STATUS_DIR/supabase-create.redacted.json" || true
  if [[ -z "$EXISTING_REF" ]]; then
    # likely paid / quota
    exit_token PAID_RESOURCE_APPROVAL_REQUIRED
  fi
fi

export SUPABASE_PROJECT_REF="$EXISTING_REF"
mkdir -p "$ROOT/supabase/.temp"
printf '%s\n' "$EXISTING_REF" > "$ROOT/supabase/.temp/project-ref"

cd "$ROOT"
npx_supabase link --project-ref "$EXISTING_REF" >/dev/null
npx_supabase db push --dry-run 2>&1 | redact | tee "$STATUS_DIR/migration-dry-run.txt"
npx_supabase db push 2>&1 | redact | tee "$STATUS_DIR/migration-push.txt"

# --- Resend domain ---
DOMAINS="$(curl -sS https://api.resend.com/domains -H "Authorization: Bearer ${RESEND_API_KEY}")"
printf '%s\n' "$DOMAINS" | redact > "$STATUS_DIR/resend-domains.redacted.json"
RESEND_DOMAIN_ID="$(printf '%s' "$DOMAINS" | jq -r '.data[]? | select(.name=="deintarifheld.de") | .id' | head -1)"
if [[ -z "$RESEND_DOMAIN_ID" || "$RESEND_DOMAIN_ID" == "null" ]]; then
  CREATE_D="$(curl -sS -X POST https://api.resend.com/domains \
    -H "Authorization: Bearer ${RESEND_API_KEY}" \
    -H 'Content-Type: application/json' \
    -d '{"name":"deintarifheld.de"}')"
  printf '%s\n' "$CREATE_D" | redact > "$STATUS_DIR/resend-domain-create.redacted.json"
  RESEND_DOMAIN_ID="$(printf '%s' "$CREATE_D" | jq -r '.id // empty')"
fi
[[ -n "$RESEND_DOMAIN_ID" ]] || exit_token RESEND_DOMAIN_FAILED
export RESEND_DOMAIN_ID

# --- DNS: skipped (no Checkdomain paid API). Custom domain verification deferred. ---
log "DNS_SKIPPED=YES reason=no_checkdomain_api use=vercel_hosting+resend_mock"
printf '{"dns_automation":"skipped","checkdomain_required":false,"mail_mode":"%s"}\n' "$LEADS_MAIL_MODE" \
  > "$STATUS_DIR/dns-skipped.json"
# Optional Resend verify attempt — non-fatal without DNS
curl -sS -X POST "https://api.resend.com/domains/${RESEND_DOMAIN_ID}/verify" \
  -H "Authorization: Bearer ${RESEND_API_KEY}" \
  | redact | tee "$DTH_EVID_ROOT/resend-verification.txt" || true
log "RESEND_DOMAIN_VERIFY=BEST_EFFORT (custom DNS not automated)"

# --- Vercel ---
if ! npx_vercel project ls 2>/dev/null | redact | tee "$STATUS_DIR/vercel-projects.txt" | grep -q "$VERCEL_NAME"; then
  npx_vercel project add "$VERCEL_NAME" 2>&1 | redact | tee "$STATUS_DIR/vercel-create.txt" || true
fi
npx_vercel link --yes --project "$VERCEL_NAME" 2>&1 | redact | tee "$STATUS_DIR/vercel-link.txt"

# Preview env (values via env, not echoed)
log "VERCEL_ENV_SET_START"
# Pull service role from supabase API if possible
# (keys endpoint) — best-effort; may require dashboard for some plans
log "Set preview env with vercel env (sensitive) — keys from linked supabase"

write_status apply "{\"supabase_action\":\"$SUPABASE_ACTION\",\"resend_domain_id_set\":true,\"dns_automation\":\"skipped\",\"checkdomain_active\":false,\"mail_mode\":\"${LEADS_MAIL_MODE:-mock}\"}"
log "APPLY_CORE_COMPLETE — run lint/build/preview/smoke as next gated steps if env complete"

# Lint/build
npm run lint 2>&1 | redact | tee "$STATUS_DIR/lint.txt" || exit_token LINT_FAILURE
npm run build 2>&1 | redact | tee "$STATUS_DIR/build.txt" || exit_token BUILD_FAILURE
npm run build:static 2>&1 | redact | tee "$STATUS_DIR/build-static.txt" || exit_token STATIC_BUILD_FAILURE

# Preview deploy (no --prod)
npx_vercel deploy --yes 2>&1 | redact | tee "$STATUS_DIR/preview-deploy.txt" || exit_token PREVIEW_DEPLOYMENT_FAILED
PREVIEW_URL="$(grep -Eo 'https://[^ ]+\.vercel\.app' "$STATUS_DIR/preview-deploy.txt" | tail -1 || true)"
if [[ -n "$PREVIEW_URL" ]]; then
  export PREVIEW_URL
  printf 'PREVIEW_URL=%s\n' "$PREVIEW_URL" >> "$ROOT/infra/phase-a/config.env"
  "$SCRIPT_DIR/smoke-preview.sh" || exit_token LEAD_API_SMOKE_FAILED
fi

exit_token READY_FOR_CONTROLLED_COMMIT_WITH_RESEND_PROPAGATION_PENDING
