#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"
load_config_if_present

export DTH_EVID_ROOT="${DTH_EVID_ROOT:-/tmp/dth-07b-credential-bootstrap-and-apply}"
STATUS_DIR="${DTH_EVID_ROOT}/status"
mkdir -p "$STATUS_DIR"

log "PLAN_START"
NS="$(dig +time=2 +tries=1 +short NS deintarifheld.de 2>/dev/null | tr '\n' ',' | sed 's/,$//' || true)"
NS="${NS:-UNRESOLVED}"

cat > "$STATUS_DIR/plan.json" <<EOF
{
  "supabase_project_name": "deintarifheld-phase-a",
  "vercel_project_name": "deintarifheld-leads-api",
  "resend_domain": "deintarifheld.de",
  "resend_from_default": "onboarding@resend.dev",
  "leads_mail_mode": "mock",
  "region": "eu-central-1",
  "max_new_monthly_cost_eur": 0,
  "dns_ns": "$NS",
  "dns_provider": "SKIPPED",
  "dns_api_available": false,
  "checkdomain_api_required": false,
  "checkdomain_paid_api": "rejected_by_owner",
  "external_credentials": ["SUPABASE_ACCESS_TOKEN","RESEND_API_KEY","CONTROLLED_TEST_EMAIL"],
  "internal_secrets_autogenerated": ["CRON_SECRET","LEADS_ADMIN_SECRET","LEADS_RATE_LIMIT_SALT"],
  "hosting": "vercel_preview",
  "production_route_swap": false,
  "phase_b": false
}
EOF

log "PLAN_WRITTEN=$STATUS_DIR/plan.json"
log "CHECKDOMAIN_API_REQUIRED=NO DNS_AUTOMATION=SKIPPED"
log "PLAN_PASS"
