#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"
load_config_if_present

# Prefer DTH-07a evidence root when present
export DTH_EVID_ROOT="${DTH_EVID_ROOT:-/tmp/dth-07a-checkdomain-api-recovery}"
STATUS_DIR="${DTH_EVID_ROOT}/status"
mkdir -p "$STATUS_DIR" "$EVID_ROOT/status" 2>/dev/null || true

log "PREFLIGHT_START"
cd "$ROOT"

[[ "$(git rev-parse --show-toplevel)" == "$ROOT" ]] || exit_token START_STATE_CONFLICT
[[ "$(git branch --show-current)" == "feat/deintarifheld-business-landingpage-foundation-001" ]] || exit_token START_STATE_CONFLICT

require_cmd node
require_cmd npm
require_cmd curl
require_cmd jq
require_cmd dig
require_cmd git
require_cmd openssl

# Auto-generate internal secrets into gitignored config.env (never print values)
ensure_internal_secrets() {
  local cfg="$ROOT/infra/phase-a/config.env"
  umask 077
  mkdir -p "$(dirname "$cfg")"
  touch "$cfg"
  chmod 0600 "$cfg"
  local changed=NO
  _append_rand_hex() {
    local key="$1" nbytes="$2"
    if grep -qE "^${key}=.+" "$cfg" 2>/dev/null; then return 0; fi
    if [[ -n "${!key-}" ]]; then return 0; fi
    # strip empty placeholder lines for key
    if grep -qE "^${key}=" "$cfg" 2>/dev/null; then
      grep -vE "^${key}=" "$cfg" > "${cfg}.tmp" || true
      mv "${cfg}.tmp" "$cfg"
    fi
    printf '%s=' "$key" >> "$cfg"
    openssl rand -hex "$nbytes" >> "$cfg"
    printf '\n' >> "$cfg"
    changed=YES
    log "${key}_AUTOGENERATED=YES"
  }
  _append_rand_hex CRON_SECRET 32
  _append_rand_hex LEADS_ADMIN_SECRET 32
  _append_rand_hex LEADS_RATE_LIMIT_SALT 16
  chmod 0600 "$cfg"
  if [[ "$changed" == "YES" ]]; then
    log "INTERNAL_SECRETS_WRITTEN_TO=infra/phase-a/config.env INTERNAL_SECRET_VALUES_PRINTED=NO"
  fi
  load_config_if_present
}

ensure_internal_secrets

# External credentials — Checkdomain intentionally NOT required (no paid API)
EXTERNAL_REQUIRED=(SUPABASE_ACCESS_TOKEN RESEND_API_KEY CONTROLLED_TEST_EMAIL)
MISSING=()
for v in "${EXTERNAL_REQUIRED[@]}"; do
  if [[ -z "${!v-}" ]]; then MISSING+=("$v"); fi
done

# Default: mock mail until custom domain is verified elsewhere (Vercel/DNS later)
cfg="$ROOT/infra/phase-a/config.env"
if [[ -f "$cfg" ]] && ! grep -qE '^LEADS_MAIL_MODE=.+' "$cfg"; then
  printf 'LEADS_MAIL_MODE=mock\n' >> "$cfg"
fi
if [[ -z "${LEADS_MAIL_MODE-}" ]]; then
  export LEADS_MAIL_MODE=mock
fi
if [[ -z "${LEADS_FROM_EMAIL-}" ]]; then
  # Resend onboarding sender works without custom-domain DNS
  export LEADS_FROM_EMAIL="DeinTarifheld <onboarding@resend.dev>"
fi

VERCEL_OK=NO
# Prefer token if set; otherwise CLI login session
if [[ -n "${VERCEL_TOKEN-}" ]] || npx_vercel whoami >/dev/null 2>&1; then VERCEL_OK=YES; fi

# DNS lookup is informational only (Checkdomain API not used)
NS="$(dig +time=1 +tries=1 +short NS deintarifheld.de 2>/dev/null | tr '\n' ' ' || true)"
NS="${NS:-SKIPPED_OR_UNRESOLVED}"

{
  echo "VERCEL_CLI_SESSION=$VERCEL_OK"
  echo "DNS_NS=$NS"
  echo "CHECKDOMAIN_API_REQUIRED=NO"
  echo "DNS_AUTOMATION=SKIPPED_USE_VERCEL_HOSTING_AND_RESEND_MOCK"
  echo "LEADS_MAIL_MODE=${LEADS_MAIL_MODE}"
  echo "INTERNAL_SECRETS_GENERATABLE=YES"
  echo "MISSING_EXTERNAL_VARS=${MISSING[*]:-NONE}"
} | tee "$STATUS_DIR/preflight.txt" | redact

python3 <<'PY' | tee -a "$STATUS_DIR/preflight.txt"
import os, hashlib
names=["SUPABASE_ACCESS_TOKEN","RESEND_API_KEY","CONTROLLED_TEST_EMAIL","CRON_SECRET","LEADS_ADMIN_SECRET"]
for n in names:
  v=os.environ.get(n,"")
  if not str(v).strip():
    print(f"{n}: PRESENT=NO LENGTH= SHA256_PREFIX= VALUE_PRINTED=NO")
  else:
    b=str(v).strip().encode()
    print(f"{n}: PRESENT=YES LENGTH={len(b)} SHA256_PREFIX={hashlib.sha256(b).hexdigest()[:12]} VALUE_PRINTED=NO")
PY

if [[ "$VERCEL_OK" != "YES" && -z "${VERCEL_TOKEN-}" ]]; then
  MISSING+=("VERCEL_CLI_SESSION_OR_TOKEN")
fi

if [[ ${#MISSING[@]} -gt 0 ]]; then
  write_status preflight "{\"ok\":false,\"missing\":$(printf '%s\n' "${MISSING[@]}" | jq -R . | jq -s .)}"
  log "Credential gaps: ${MISSING[*]}"
  exit_token AUTOMATION_CREDENTIALS_REQUIRED
fi

write_status preflight '{"ok":true,"checkdomain_provider":true}'
log "PREFLIGHT_PASS"
