/** @deintarifheld/shared — P3-F0/F1/F6 foundation exports */
export { DTH_PACKAGE_SKELETON } from './skeleton.js';
export {
  PrincipalType,
  createPersonPrincipal,
  createServicePrincipal,
  createBreakGlassPrincipal,
  isPersonPrincipal,
} from './principal.js';
export { issueCcSession, rejectSharedSecretAsCcSession } from './session.js';
export { auditActorFromCcSession } from './audit-actor.js';
export {
  KillDomain,
  KILL_DOMAINS,
  KILL_DOMAIN_COUNT,
  isKillDomain,
  assertExactKillDomainSet,
} from './kill-domains.js';
export { KillState, isKillState, evaluateCapabilityEnabled } from './kill-state.js';
export { LOCAL_DEV_KILL_DEFAULTS, createDefaultKillRegistry } from './kill-defaults.js';
export {
  SotResourceType,
  SotPersistenceTarget,
  SOT_ALIAS_MAP,
  COMMUNICATION_EVENT_SOT_TYPE,
  CASE_NOTE_SOT_TYPE,
  resolveSotAlias,
} from './sot-alias.js';
export {
  CcPrimaryView,
  InboxRequestKind,
  InboxAssignmentStatus,
  redactEmail,
  buildInboxItemFromLead,
  buildInboxItemFromCareer,
} from './cc-read-models.js';
export {
  SYNTHETIC_NOOP_EVENT_TYPE,
  SYNTHETIC_NOOP_PAYLOAD,
  isAuthorizedSyntheticNoopEvent,
} from './synthetic-noop.js';
export {
  AutomationActivation,
  LOCAL_TEST_FLAG_NAME,
  PersistenceAdapterKind,
  ExternalEffectAdapterKind,
  resolveAutomationActivation,
  resolveLocalTestFlag,
  evaluateWorkerMayProcess,
} from './worker-activation.js';
export {
  WorkerRunResultCode,
  WorkerErrorClass,
  MAX_JOBS_PER_TEST_RUN,
} from './outbox-consumer-contracts.js';

/* DTH-A1 durable workflow runtime contracts */
export {
  JOB_DELIVERY_SEMANTICS,
  PRODUCTION_EXACTLY_ONCE_GUARANTEE,
  EXTERNAL_EFFECT_ADAPTER_DEFAULT,
  PRODUCTION_AUTONOMY_ALLOWED,
  WorkflowStatus,
  JobStatus,
  ControlScope,
  ControlStateValue,
  WorkflowErrorClass,
  RETRYABLE_ERROR_CLASSES,
  RECONCILIATION_ERROR_CLASSES,
  SyntheticCapability,
  A1_WORKFLOW_TYPE,
  A1_WORKFLOW_VERSION,
  A2_HANDOFF_EVENT_TYPE,
  RuntimeLimits,
  isRetryableErrorClass,
  requiresReconciliation,
} from './workflow-runtime-contracts.js';

/* DTH-A4 Communication Engine contracts */
export {
  A4_COMMUNICATION_POLICY_ID,
  A4_COMMUNICATION_POLICY_VERSION,
  A4_TEMPLATE_MISSING_INFO_ID,
  A4_TEMPLATE_MISSING_INFO_VERSION,
  A4_TEST_FOLLOWUP_DELAY_MS,
  A4_DEFAULT_MAX_FOLLOWUPS,
  OWNER_FOLLOWUP_CADENCE_REQUIRED,
  B2B_MISSING_INFO_COMMUNICATE_CAPABILITY,
  B2B_COMMUNICATION_SEND_CAPABILITY,
  B2B_MISSING_INFO_FOLLOWUP_CAPABILITY,
  B2B_INBOUND_EMAIL_PROCESS_CAPABILITY,
  B2B_APPOINTMENT_OFFER_PREPARE_CAPABILITY,
  MessagePurpose,
  ALLOWED_MESSAGE_PURPOSES,
  APPOINTMENT_MESSAGE_PURPOSES,
  OFFER_MESSAGE_PURPOSES,
  SWITCH_MESSAGE_PURPOSES,
  LIFECYCLE_MESSAGE_PURPOSES,
  OutboundIntentState,
  ConversationStatus,
  InboundEventStatus,
  FollowupStatus,
  FIELD_LABEL_DE,
  isAllowedMessagePurpose,
  isAppointmentMessagePurpose,
  isOfferMessagePurpose,
  isSwitchMessagePurpose,
  isLifecycleMessagePurpose,
  PROVIDER_EVENT_PRECEDENCE,
} from './a4-communication-contracts.js';

/* DTH-A5 Calendar + Appointment contracts */
export {
  A5_APPOINTMENT_POLICY_ID,
  A5_APPOINTMENT_POLICY_VERSION,
  A5_CALENDAR_RESOURCE_DEFAULT,
  A5_PROVIDER_TEST,
  AppointmentPurpose,
  ALLOWED_APPOINTMENT_PURPOSES,
  BookingSessionStatus,
  AppointmentStatus,
  ConferenceStatus,
  ReminderStatus,
  APPOINTMENT_OFFER_PREPARE_CAPABILITY,
  APPOINTMENT_BOOK_SELECTED_SLOT_CAPABILITY,
  APPOINTMENT_RECONCILE_CAPABILITY,
  APPOINTMENT_REMINDER_DUE_CAPABILITY,
  APPOINTMENT_CANCEL_CAPABILITY,
  APPOINTMENT_RESCHEDULE_CAPABILITY,
  APPOINTMENT_SESSION_EXPIRE_CAPABILITY,
  A5_TEMPLATE_OFFER_ID,
  A5_TEMPLATE_CONFIRM_ID,
  A5_TEMPLATE_REMINDER_ID,
  A5_TEMPLATE_VERSION,
  OWNER_CALL_DURATION_REQUIRED,
  OWNER_TIMEZONE_REQUIRED,
  OWNER_WORKING_HOURS_REQUIRED,
  OWNER_MIN_LEAD_TIME_REQUIRED,
  OWNER_BOOKING_HORIZON_REQUIRED,
  OWNER_BUFFER_POLICY_REQUIRED,
  OWNER_SLOT_COUNT_REQUIRED,
  OWNER_BOOKING_EXPIRY_REQUIRED,
  OWNER_REMINDER_POLICY_REQUIRED,
  OWNER_RESCHEDULE_POLICY_REQUIRED,
  OWNER_CANCELLATION_POLICY_REQUIRED,
  OWNER_NO_BOOKING_POLICY_REQUIRED,
  OWNER_CALENDAR_PROVIDER_DECISION_REQUIRED,
  APPOINTMENT_RETENTION_POLICY_REQUIRED,
  TEST_APPOINTMENT_POLICY_V1,
  isAllowedAppointmentPurpose,
  eligibilityFingerprint,
} from './a5-appointment-contracts.js';

/* DTH-A6 Document Intelligence contracts */
export {
  A6_DOCUMENT_POLICY_ID,
  A6_DOCUMENT_POLICY_VERSION,
  A6_EXTRACTOR_ID,
  A6_EXTRACTOR_VERSION,
  A6_CLASSIFIER_ID,
  A6_CLASSIFIER_VERSION,
  TEST_MAX_DOCUMENT_BYTES,
  TEST_MAX_EXTRACTED_TEXT_CHARS,
  LIVE_DOCUMENT_STORAGE_PROVIDER_CALLS,
  LIVE_OCR_PROVIDER_CALLS,
  LIVE_AI_CALLS_A6,
  DOCUMENT_INTELLIGENCE_PREPARE_CAPABILITY,
  DOCUMENT_PROCESS_CAPABILITY,
  ENERGY_TARIFF_EVALUATION_PREPARE_HANDOFF,
  DocumentSourceKind,
  DocumentStatus,
  DocumentType,
  OcrStatus,
  DocumentFactStatus,
  ConfidenceClass,
  FactConfidenceClass,
  FactValueType,
  DocumentFactCode,
  DocumentFactsReadiness,
  OWNER_DOCUMENT_STORAGE_PROVIDER_REQUIRED,
  OWNER_OCR_PROVIDER_DECISION_REQUIRED,
  OWNER_DOCUMENT_RETENTION_POLICY_REQUIRED,
  OWNER_CUSTOMER_UPLOAD_UI_DECISION_REQUIRED,
  OWNER_DOCUMENT_REQUEST_COMMUNICATION_REQUIRED,
  OWNER_MALWARE_SCANNER_PROVIDER_REQUIRED,
  DocumentKillDomain,
} from './a6-document-contracts.js';

/* DTH-A7 Energy + Tariff Domain contracts */
export {
  ENERGY_TARIFF_EVALUATION_PREPARE_CAPABILITY,
  OFFER_PREPARE_HANDOFF,
  A7_CALCULATION_POLICY_ID,
  A7_CALCULATION_POLICY_VERSION,
  A7_RANKING_POLICY_ID,
  A7_RANKING_POLICY_VERSION,
  A7_EXTRACTOR_ID,
  A7_EXTRACTOR_VERSION,
  A7_ELIGIBILITY_POLICY_ID,
  A7_ELIGIBILITY_POLICY_VERSION,
  MICRO_EUR_SCALE,
  LIVE_TARIFF_PROVIDER_CALLS,
  LIVE_SUPPLIER_API_CALLS,
  LIVE_AI_CALLS_A7,
  TariffStatus,
  EnergyType,
  CustomerSegment,
  PriceBasis,
  ComponentType,
  ComponentFrequency,
  ComponentAppliesTo,
  EligibilityStatus,
  EvaluationReadiness,
  EvaluationStatus,
  EligibilityReasonCode,
  EligibilityRuleType,
  TariffSourceKind,
  ProfileReadiness,
  BaselineSource,
  OWNER_LIVE_TARIFF_SOURCE_REQUIRED,
  OWNER_TARIFF_RANKING_POLICY_REQUIRED,
  OWNER_ENERGY_BUSINESS_RULE_REQUIRED,
  OWNER_VAT_TAX_POLICY_REQUIRED,
  OWNER_TARIFF_IMPORT_PROVIDER_REQUIRED,
  OWNER_COMMISSION_DATA_POLICY_REQUIRED,
  TariffKillDomain,
} from './a7-tariff-contracts.js';

/* DTH-A8 Offer Engine contracts */
export {
  OFFER_PREPARE_CAPABILITY,
  OFFER_APPROVAL_REQUEST_CAPABILITY,
  OFFER_DELIVER_CAPABILITY,
  OFFER_FOLLOWUP_DUE_CAPABILITY,
  OFFER_EXPIRE_CAPABILITY,
  OFFER_ACCEPT_CAPABILITY,
  OFFER_REJECT_CAPABILITY,
  OFFER_RECONCILE_CAPABILITY,
  SWITCH_PREPARATION_CAPABILITY,
  A8_OFFER_POLICY_ID,
  A8_OFFER_POLICY_VERSION,
  A8_APPROVAL_POLICY_ID,
  A8_APPROVAL_POLICY_VERSION,
  A8_TEMPLATE_ID,
  A8_TEMPLATE_VERSION,
  LIVE_AI_CALLS_A8,
  LIVE_EMAIL_SENDS_A8,
  LIVE_TARIFF_PROVIDER_CALLS_A8,
  LIVE_SUPPLIER_API_CALLS_A8,
  SUPPLIER_SWITCH_ACTIONS,
  OfferEnvironment,
  OfferSelectionMode,
  OfferSourceKind,
  OfferEnvironmentMarker,
  OfferCustomerLiveMarker,
  SavingsUnknownPresentation,
  NegativeSavingsPresentation,
  FirstYearVsOngoing,
  OfferState,
  OfferApprovalDecision,
  OfferApprovalActorType,
  OfferCustomerDecision,
  OfferDecisionChannel,
  SwitchPreparationStatus,
  OWNER_OFFER_SELECTION_POLICY_REQUIRED,
  OWNER_OFFER_APPROVAL_POLICY_REQUIRED,
  OWNER_OFFER_FOLLOWUP_POLICY_REQUIRED,
  OWNER_OFFER_LEGAL_TEXT_REQUIRED,
  OFFER_RETENTION_POLICY_REQUIRED,
  OfferKillDomain,
  SYNTHETIC_OFFER_LEGAL_TEXT_DE,
} from './a8-offer-contracts.js';

/* DTH-A9 Switching Workflow contracts */
export {
  SWITCH_SUBMIT_CAPABILITY,
  SWITCH_RECONCILE_CAPABILITY,
  CUSTOMER_LIFECYCLE_PREPARE_CAPABILITY,
  A9_SWITCHING_POLICY_ID,
  A9_SWITCHING_POLICY_VERSION,
  A9_SUBMISSION_POLICY_ID,
  A9_SUBMISSION_POLICY_VERSION,
  A9_PAYLOAD_VERSION,
  A9_TEST_PROVIDER_CODE,
  LIVE_SWITCH_PROVIDER_CALLS,
  LIVE_SUPPLIER_API_CALLS_A9,
  LIVE_AI_CALLS_A9,
  SwitchType,
  SwitchReadiness,
  SwitchCaseStatus,
  SwitchAttemptState,
  SwitchStatusRank,
  SwitchFieldCode,
  SwitchFactSource,
  SwitchRequirementCode,
  SwitchRejectionCategory,
  SwitchApprovalDecision,
  OWNER_LIVE_SWITCH_PROVIDER_REQUIRED,
  OWNER_SWITCH_SUBMISSION_POLICY_REQUIRED,
  OWNER_MULTI_SUPPLY_SWITCH_POLICY_REQUIRED,
  SWITCH_RETENTION_POLICY_REQUIRED,
  OWNER_PAYMENT_DATA_HANDLING_REVIEW_REQUIRED,
  SwitchKillDomain,
  SWITCH_FIELD_LABEL_DE,
} from './a9-switching-contracts.js';

/* DTH-A10 Customer Lifecycle + Renewal */
export {
  LIFECYCLE_ACTIVATE_DUE_CAPABILITY,
  LIFECYCLE_RECONCILE_CAPABILITY,
  RENEWAL_WINDOW_OPEN_CAPABILITY,
  RENEWAL_EVALUATION_PREPARE_CAPABILITY,
  RENEWAL_OFFER_PREPARE_CAPABILITY,
  A10_DATE_POLICY_ID,
  A10_DATE_POLICY_VERSION,
  A10_ACTIVATION_POLICY_ID,
  A10_ACTIVATION_POLICY_VERSION,
  A10_RENEWAL_POLICY_ID,
  A10_RENEWAL_POLICY_VERSION,
  A10_EVIDENCE_POLICY_ID,
  A10_TEST_POLICY_MARKER,
  LIVE_LIFECYCLE_PROVIDER_CALLS,
  LIVE_AI_CALLS_A10,
  A10_RECOMPUTED_TARIFF_PRICING,
  OfferPurpose,
  LifecycleStatus,
  LifecycleStatusRank,
  RenewalCycleStatus,
  LifecycleException,
  OWNER_RENEWAL_POLICY_REQUIRED,
  OWNER_RENEWAL_COMMUNICATION_POLICY_REQUIRED,
  CUSTOMER_LIFECYCLE_RETENTION_POLICY_REQUIRED,
  OWNER_LIFECYCLE_PROVIDER_DECISION_REQUIRED,
  LifecycleKillDomain,
} from './a10-lifecycle-contracts.js';
/* DTH-A3 B2B qualification contracts */
export {
  A3_POLICY_ID,
  A3_POLICY_VERSION,
  QUALIFICATION_SCOPE,
  B2B_QUALIFICATION_REEVALUATE_CAPABILITY,
  QualificationOutcome,
  RequirementStatus,
  ObservationSourceKind,
  FieldCode,
  OBSERVATION_FIELD_ALLOWLIST,
  ReasonCode,
  FieldRequirementClass,
  CanonicalEnergyType,
  WorkflowQualState,
  isObservationFieldAllowed,
  workflowStateForOutcome,
} from './a3-qualification-contracts.js';

/* DTH-A2 Lead → Case contracts */
export {
  BUSINESS_LEAD_ACCEPTED_EVENT,
  BUSINESS_LEAD_ACCEPTED_SCHEMA_VERSION,
  B2B_INBOUND_WORKFLOW_TYPE,
  B2B_INBOUND_WORKFLOW_VERSION,
  B2B_QUALIFICATION_START_CAPABILITY,
  LeadType,
  SOURCE_LEAD_STATUS_AFTER_ACCEPT,
  CASE_INITIAL_STATUS,
  WORKFLOW_INITIAL_STATE,
  FIRST_JOB_TYPE,
  buildBusinessLeadAcceptedPayload,
  isBusinessEnergyLeadType,
} from './a2-lead-case-contracts.js';

/* P4-H0a — local production-identity foundation (synthetic provider evidence) */
export {
  IdentityProvider,
  PRODUCTION_CC_ORIGIN,
  PRODUCTION_AUTH_UI_ORIGIN,
  PASSKEY_RP_ID,
  EXPECTED_AUTHORIZED_PARTY,
  EXPECTED_AUDIENCE,
  PRODUCTION_AUDIENCE_VALUE_DEFINED,
  DEVELOPMENT_AUTHORIZED_PARTY,
  LOCAL_CC_ORIGIN,
  AUTHORIZED_PARTY_ALLOWLIST,
  AUTHORIZED_PARTY_WILDCARDS_ALLOWED,
  SESSION_INACTIVITY_TIMEOUT_MINUTES,
  SESSION_MAXIMUM_LIFETIME_HOURS,
  MAX_ACTIVE_SESSIONS_PER_DTH_PERSON,
  MULTI_SESSION_ALLOWED,
  LinkStatus,
  PasskeyPolicy,
  AuthAssuranceMethod,
} from './identity/h0a-constants.js';
export { TokenErrorCode } from './identity/token-errors.js';
export { createStaticJwksAdapter } from './identity/jwks-adapter.js';
export {
  deriveDevelopmentJwksEndpoints,
  validateExactDevelopmentJwksUrl,
} from './identity/jwks-url-policy.js';
export {
  createRemoteJwksAdapter,
  parseAndValidateJwks,
  JWKS_CACHE_TTL_SECONDS,
  JWKS_TOTAL_TIMEOUT_MILLISECONDS,
  JWKS_MAX_RESPONSE_BYTES,
  JWKS_MAX_KEYS,
  UNKNOWN_KID_FORCED_REFRESH_COUNT,
  AUTOMATIC_RETRY_COUNT,
  STALE_JWKS_AFTER_TTL_ALLOWED,
  REDIRECTS_ALLOWED,
} from './identity/remote-jwks-adapter.js';
export { validateProviderToken } from './identity/token-validator.js';
export {
  createInMemoryPersonMappingAdapter,
  rejectEmailBasedAutoMapping,
  rejectAutomaticPersonCreation,
} from './identity/person-mapping.js';
export {
  createInMemoryActiveSessionAdapter,
  evaluateSessionPolicy,
  PRODUCTION_CONCURRENT_SESSION_RESOLUTION,
  CONCURRENT_SESSION_POLICY,
} from './identity/session-policy.js';
export {
  createInMemoryProviderSessionRegistry,
  applyProviderSessionLifecycle,
  markProviderSessionRevoked,
} from './identity/provider-session-lifecycle.js';
export {
  getPasskeyEnrollmentPolicyContract,
  evaluateOperationalPasskeyAssurance,
} from './identity/passkey-policy.js';
export {
  authenticateProviderTokenToPersonPrincipal,
  rejectNonPersonAsPersonSession,
} from './identity/authenticate-provider-token.js';
export {
  createEphemeralRs256TestFixture,
  SYNTHETIC_ISSUER,
  SYNTHETIC_AUDIENCE,
} from './identity/synthetic-test-keys.js';

/* DTH-A11 Production Command Center */
export {
  A11_COMMAND_CENTER_POLICY_ID,
  A11_COMMAND_CENTER_POLICY_VERSION,
  A11_STAGE_POLICY_ID,
  A11_STAGE_POLICY_VERSION,
  A11_INBOX_POLICY_ID,
  A11_INBOX_POLICY_VERSION,
  OWNER_COMMAND_CENTER_AUTH_PROVIDER_REQUIRED,
  OWNER_OPERATOR_SESSION_POLICY_REQUIRED,
  OWNER_COMMAND_CENTER_DEPLOYMENT_DECISION_REQUIRED,
  OWNER_COMMAND_CENTER_ROLE_POLICY_REQUIRED,
  OWNER_AUDIT_RETENTION_POLICY_REQUIRED,
  STRONG_AUTHZ_COMPLETE,
  STAGING_COMMAND_CENTER_READY,
  PRODUCTION_COMMAND_CENTER_READY,
  STAGING_AUTONOMY_READY,
  PRODUCTION_AUTONOMY_READY,
  A11_LIVE_AI_CALLS,
  OperatorRole,
  OperatorCapability,
  ROLE_CAPABILITIES,
  TEST_OPERATOR_IDENTITIES,
  TEST_OPERATOR_BY_PERSON_ID,
  TEST_OPERATOR_STABLE_IDS,
  TEST_OPERATOR_ID_BY_PERSON_ID,
  A11_PROTECTED_VIEW_CAPABILITY,
  OperatorCommandType,
  COMMAND_REQUIRED_CAPABILITY,
  HIGH_RISK_COMMANDS,
  COMMANDS_REQUIRING_REASON,
  ReconcileDomain,
  ExceptionSeverity,
  WaitingOn,
  CaseStage,
  A11ErrorCode,
  A11ReadLimit,
  OPERATOR_COMMAND_MAX_BYTES,
  capabilitiesForRole,
  roleHasCapability,
  isOperatorCommandType,
  isHighRiskCommand,
} from './a11-command-center-contracts.js';

/* DTH-A12 Content Autopilot */
export {
  A12_STRATEGY_POLICY_ID,
  A12_STRATEGY_POLICY_VERSION,
  A12_BRAND_POLICY_ID,
  A12_BRAND_POLICY_VERSION,
  A12_RISK_POLICY_ID,
  A12_RISK_POLICY_VERSION,
  A12_APPROVAL_POLICY_ID,
  A12_APPROVAL_POLICY_VERSION,
  A12_TEST_GENERATOR_ID,
  A12_TEST_PUBLISHER_ID,
  LIVE_AI_CALLS_A12,
  LIVE_SOCIAL_PROVIDER_CALLS,
  LIVE_CONTENT_PUBLICATIONS,
  STAGING_CONTENT_AUTONOMY_READY,
  PRODUCTION_CONTENT_AUTONOMY_READY,
  STAGING_AUTONOMY_READY_A12,
  PRODUCTION_AUTONOMY_READY_A12,
  OWNER_CONTENT_STRATEGY_POLICY_REQUIRED,
  OWNER_CONTENT_PUBLISHING_PROVIDER_REQUIRED,
  OWNER_CONTENT_AI_PROVIDER_REQUIRED,
  OWNER_CONTENT_AUTOPUBLISH_POLICY_REQUIRED,
  CONTENT_PUBLICATION_DUE_CAPABILITY,
  CONTENT_RECONCILE_CAPABILITY,
  CONTENT_METRICS_REFRESH_CAPABILITY,
  ContentKillDomain,
  ContentPurpose,
  ContentAudience,
  ContentChannel,
  ContentStatus,
  ClaimType,
  ClaimState,
  ContentRiskClass,
  ContentApprovalDecision,
  ContentIntentState,
  ContentPublicationState,
  ContentGeneratorMode,
  ALLOWED_CONTENT_DOMAINS,
  FORBIDDEN_CLAIM_PATTERNS,
  BRAND_RULES_V1,
  ContentStrategyPolicyV1,
  BrandPolicyV1,
  ContentRiskPolicyV1,
  ContentApprovalPolicyV1,
} from './a12-content-contracts.js';


/* DTH-A13 Acquisition Autopilot */
export {
  A13_ATTRIBUTION_POLICY_ID,
  A13_ATTRIBUTION_POLICY_VERSION,
  A13_BUDGET_POLICY_ID,
  A13_BUDGET_POLICY_VERSION,
  A13_APPROVAL_POLICY_ID,
  A13_APPROVAL_POLICY_VERSION,
  A13_TEST_PROVIDER_ID,
  A13_TEST_PROVIDER_ACCOUNT,
  LIVE_AD_SPEND_EUR,
  LIVE_AD_PROVIDER_CALLS,
  LIVE_PAID_CAMPAIGN_ACTIVATIONS,
  LIVE_AI_CALLS_A13,
  STAGING_ACQUISITION_AUTONOMY_READY,
  PRODUCTION_ACQUISITION_AUTONOMY_READY,
  STAGING_AUTONOMY_READY_A13,
  PRODUCTION_AUTONOMY_READY_A13,
  OWNER_ACQUISITION_ATTRIBUTION_POLICY_REQUIRED,
  OWNER_ACQUISITION_BUDGET_POLICY_REQUIRED,
  OWNER_ACQUISITION_TRACKING_POLICY_REQUIRED,
  OWNER_ACQUISITION_KILL_BEHAVIOR_REQUIRED,
  OWNER_ACQUISITION_PROVIDER_REQUIRED,
  OWNER_ACQUISITION_AD_ACCOUNT_REQUIRED,
  ACQUISITION_CAMPAIGN_ACTIVATE_DUE_CAPABILITY,
  ACQUISITION_CAMPAIGN_RECONCILE_CAPABILITY,
  ACQUISITION_METRICS_REFRESH_CAPABILITY,
  AcquisitionKillDomain,
  AcquisitionSourceKind,
  CampaignObjective,
  CampaignStatus,
  CampaignIntentState,
  CampaignIntentKind,
  TouchpointType,
  AttributionState,
  AcquisitionApprovalDecision,
  AcquisitionProviderCampaignState,
  ALLOWED_ACQUISITION_DESTINATION_HOSTS,
  ALLOWED_ACQUISITION_DESTINATION_PATH_PREFIXES,
  AcquisitionAttributionPolicyV1,
  AcquisitionBudgetPolicyV1,
  AcquisitionApprovalPolicyV1,
  AcquisitionProviderMode,
  A14HandoffCategory,
  A13_CRITICAL_INVARIANT_KEYS,
  A13_CRITICAL_INVARIANT_EXPECTED,
} from './a13-acquisition-contracts.js';
