/**
 * Evidence-bound production-readiness projection. UNKNOWN never becomes PASS.
 */
import {
  OWNER_COMMAND_CENTER_AUTH_PROVIDER_REQUIRED,
  OWNER_OPERATOR_SESSION_POLICY_REQUIRED,
  OWNER_COMMAND_CENTER_DEPLOYMENT_DECISION_REQUIRED,
  STRONG_AUTHZ_COMPLETE,
  STAGING_COMMAND_CENTER_READY,
  PRODUCTION_COMMAND_CENTER_READY,
  STAGING_AUTONOMY_READY,
  PRODUCTION_AUTONOMY_READY,
  OWNER_DOCUMENT_STORAGE_PROVIDER_REQUIRED,
  OWNER_OCR_PROVIDER_DECISION_REQUIRED,
  OWNER_LIVE_TARIFF_SOURCE_REQUIRED,
  OWNER_OFFER_APPROVAL_POLICY_REQUIRED,
  OWNER_OFFER_LEGAL_TEXT_REQUIRED,
  OWNER_LIVE_SWITCH_PROVIDER_REQUIRED,
  OWNER_RENEWAL_POLICY_REQUIRED,
  OWNER_LIFECYCLE_PROVIDER_DECISION_REQUIRED,
  OWNER_CALENDAR_PROVIDER_DECISION_REQUIRED,
  PRODUCTION_AUTONOMY_ALLOWED,
} from '@deintarifheld/shared';

function gate(id, required, evidence) {
  if (required) {
    return { id, status: 'BLOCKED', evidence, maturity: 'E2_LOCAL' };
  }
  return { id, status: 'UNKNOWN', evidence, maturity: 'E2_LOCAL' };
}

export function getProductionReadinessView() {
  const gates = [
    gate('A4_LIVE_MAIL', true, 'OWNER_LIVE_MAIL_NOT_PROVEN'),
    gate('A5_LIVE_CALENDAR', OWNER_CALENDAR_PROVIDER_DECISION_REQUIRED, 'OWNER_CALENDAR_PROVIDER_DECISION_REQUIRED'),
    gate('A6_STORAGE_OCR', OWNER_DOCUMENT_STORAGE_PROVIDER_REQUIRED || OWNER_OCR_PROVIDER_DECISION_REQUIRED, 'OWNER_DOCUMENT_STORAGE_OR_OCR_REQUIRED'),
    gate('A7_LIVE_TARIFFS', OWNER_LIVE_TARIFF_SOURCE_REQUIRED, 'OWNER_LIVE_TARIFF_SOURCE_REQUIRED'),
    gate('A8_COMMERCIAL', OWNER_OFFER_APPROVAL_POLICY_REQUIRED || OWNER_OFFER_LEGAL_TEXT_REQUIRED, 'OWNER_OFFER_POLICY_REQUIRED'),
    gate('A9_SWITCH_PROVIDER', OWNER_LIVE_SWITCH_PROVIDER_REQUIRED, 'OWNER_LIVE_SWITCH_PROVIDER_REQUIRED'),
    gate('A10_LIFECYCLE', OWNER_RENEWAL_POLICY_REQUIRED || OWNER_LIFECYCLE_PROVIDER_DECISION_REQUIRED, 'OWNER_LIFECYCLE_POLICY_REQUIRED'),
    gate('M11_SECURITY', true, 'M11F_G_PLUS_RUNTIME_ROLES_NOT_PROVEN'),
    gate('OPERATOR_AUTH', OWNER_COMMAND_CENTER_AUTH_PROVIDER_REQUIRED, 'OWNER_COMMAND_CENTER_AUTH_PROVIDER_REQUIRED'),
    gate('OPERATOR_SESSION', OWNER_OPERATOR_SESSION_POLICY_REQUIRED, 'OWNER_OPERATOR_SESSION_POLICY_REQUIRED'),
    gate('CC_DEPLOYMENT', OWNER_COMMAND_CENTER_DEPLOYMENT_DECISION_REQUIRED, 'OWNER_COMMAND_CENTER_DEPLOYMENT_DECISION_REQUIRED'),
    gate('STRONG_AUTHZ', !STRONG_AUTHZ_COMPLETE, 'STRONG_AUTHZ_COMPLETE=NO'),
  ];
  return {
    ok: true,
    generatedAt: new Date().toISOString(),
    maturity: 'E2_LOCAL',
    realtime: false,
    productionAutonomyAllowed: PRODUCTION_AUTONOMY_ALLOWED,
    stagingCommandCenterReady: STAGING_COMMAND_CENTER_READY,
    productionCommandCenterReady: PRODUCTION_COMMAND_CENTER_READY,
    stagingAutonomyReady: STAGING_AUTONOMY_READY,
    productionAutonomyReady: PRODUCTION_AUTONOMY_READY,
    falseGreens: 0,
    gates,
    overall: 'NOT_READY',
  };
}
